version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-data: